impo<div className="p-4 border rounded-lg w-full sm:w-1/2 md:w-1/3 lg:w-1/4">
  <img src={product.image} alt={product.name} className="w-full h-40 object-cover" />
  <h3 className="text-lg font-bold mt-2">{product.name}</h3>
  <p className="text-gray-600">{product.price} KES</p>
</div>
import { CartProvider } from "@/lib/CartContext";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
rtimport { Toaster } from 'react-hot-toast';

<link rel="manifest" href="/manifest.json" />
<meta name="theme-color" content="#0ea5e9" />
<link rel="apple-touch-icon" href="/icon-192x192.png" />
<link rel="manifest" href="/manifest.json" />
<meta name="theme-color" content="#1e40af" />
// supa-app/app/layout.tsx
import React from "react";
import "./globals.css"; // import your global styles if you have them

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Supa App</title>
      </head>
      <body className="bg-gray-50 min-h-screen">
        <div className="container mx-auto p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
